CREATE TABLE STUDENTS
(STUID INT ,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(50),
CITY VARCHAR(25),
DIVISION VARCHAR(20));

INSERT INTO STUDENTS
VALUES(1011,'KEYUR','PATEL','technothenet.com','RAJKOT','II-BCX'),
	  (1022,'HARDIK','SHAH','digminecraft.com','AHEMDABAD','I-BCY'),
	  (1033,'KAJAL','TRIVEDI','bigactivities.com','BARODA','IV-DCX'),
	  (1044,'BHOOMI','GAJERA','checkyourmath.com','AHEMDABAD','III-DCW'),
	  (1055,'HRMIT','MITEL',NULL,'RAJKOT','II-BCY'),
	  (1066,'ASHOK','JANI',NULL,'BARODA','II-BCZ');

SELECT * FROM STUDENTS

--1
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'K%'

--2
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE '_____'

--3
SELECT FIRSTNAME,LASTNAME,CITY FROM STUDENTS WHERE CITY LIKE '______A'

--4
SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%TEL'

--5
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'HA%T'

--6
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'K_Y%'

--7
SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'

--8
SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%JER%'

--9
SELECT * FROM STUDENTS WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'

--10
SELECT * FROM STUDENTS WHERE WEBSITE IS NOT NULL

--11
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '[A-H]%'

--12
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '_[AEIOU]%'

--13
SELECT FIRSTNAME FROM STUDENTS WHERE CITY LIKE '%ROD%'

--14
SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE WEBSITE LIKE 'BI%'

--15
SELECT CITY FROM STUDENTS WHERE LASTNAME LIKE '______'

--16 
SELECT * FROM STUDENTS WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%'

--17
SELECT * FROM STUDENTS WHERE DIVISION LIKE 'II'

--18
SELECT FIRSTNAME,DIVISION FROM STUDENTS WHERE DIVISION LIKE '%B%C%'

--19
SELECT STUID, CITY FROM STUDENTS WHERE DIVISION LIKE '______' AND WEBSITE IS NOT NULL

--20
SELECT * FROM STUDENTS WHERE FIRSTNAME NOT LIKE '__[AEIOU]%'
