CREATE TABLE STUDENT
(RNO INT,
NAME VARCHAR(50),
BRANCH VARCHAR(50));


INSERT INTO STUDENT
VALUES(101,'RAJU','CE'),
	  (102,'AMIT','CE'),
	  (103,'SANJAY','ME'),
	  (104,'NEHA','EC'),
	  (105,'MEERA','EE'),
	  (106,'MAHESH','ME');

SELECT * FROM STUDENT;

CREATE TABLE RESULT 
(RNO INT,
SPI DECIMAL(4,2));

INSERT INTO RESULT
VALUES(101,8.8),
	  (102,9.2),
	  (103,7.6),
	  (104,8.2),
	  (105,7.0),
	  (106,8.9);

SELECT * FROM RESULT

CREATE TABLE EMPLOYEES
(EMPLOYEENO VARCHAR(50),
NAME VARCHAR(50),
MANAGERNO VARCHAR(50));

INSERT INTO EMPLOYEES
VALUES('E01','TARUN',NULL),
	  ('E02','ROHAN','EO2'),
	  ('E03','PRIYA','EO1'),
	  ('E04','MILAN','EO3'),
	  ('E05','JAY','EO1'),
	  ('E06','ANJANA','E04');

SELECT * FROM EMPLOYEES

--1
SELECT * FROM STUDENT
CROSS JOIN RESULT

--OR
SELECT * FROM STUDENT,RESULT

--2
SELECT STUDENT.RNO,
	   STUDENT.NAME,
	   STUDENT.BRANCH,
	   RESULT.SPI
FROM STUDENT
LEFT OUTER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO
WHERE STUDENT.BRANCH = 'CE' 

--3
SELECT STUDENT.RNO,
	   STUDENT.NAME,
	   STUDENT.BRANCH,
	   RESULT.SPI
FROM STUDENT
RIGHT OUTER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO
WHERE STUDENT.BRANCH <> 'EC'

--4
SELECT STUDENT.BRANCH,
AVG(RESULT.SPI) AS AVG_SPI
FROM STUDENT INNER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO
GROUP BY STUDENT.BRANCH

--5
SELECT STUDENT.BRANCH,
AVG(RESULT.SPI) AS AVG_SPI
FROM STUDENT INNER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY AVG(RESULT.SPI)

--6
SELECT STUDENT.BRANCH,
	   AVG(RESULT.SPI) AS AVG_SPI
FROM STUDENT
INNER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO
AND(STUDENT.BRANCH IN ('CE','ME'))
GROUP BY STUDENT.BRANCH

--7
SELECT STUDENT.RNO,
	   STUDENT.NAME,
	   STUDENT.BRANCH,
	   RESULT.SPI
FROM STUDENT
LEFT OUTER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO

--8
SELECT STUDENT.RNO,
	   STUDENT.NAME,
	   STUDENT.BRANCH,
	   RESULT.SPI
FROM STUDENT
RIGHT OUTER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO

--9
SELECT STUDENT.RNO,
	   STUDENT.NAME,
	   STUDENT.BRANCH,
	   RESULT.SPI
FROM STUDENT
FULL OUTER JOIN RESULT
ON STUDENT.RNO = RESULT.RNO

--10
SELECT E.NAME AS EMPLOYEESNAME,
	   M.NAME AS MANAGERNAME
FROM EMPLOYEES E
LEFT OUTER JOIN EMPLOYEE M
ON E.MANAGERNO = M.EMPLOYEENO





CREATE TABLE CITY
(CITYID INT,
CITYNAME VARCHAR(50),
PINCODE VARCHAR(6),
REMARKS VARCHAR(250));

INSERT INTO CITY
VALUES(1,'RAJKOT',360005,'GOOD'),
	  (2,'SURAT',335009,'VERY GOOD'),
	  (3,'BARODA',390001,'AWESOME'),
	  (4,'JAMNAGAR',361003,'SMART'),
	  (5,'JUNAGADH',362229,'HISTORIC'),
	  (6,'MORBI',363641,'CERAMIC');

SELECT * FROM CITY;

CREATE TABLE VILLAGE
(VILLAGEID INT,
VILLAGENAME VARCHAR(50),
CITYID INT);

INSERT INTO VILLAGE
VALUES(101,'RAIYA',1),
	  (102,'MADHAPAR',1),
	  (103,'DODKA',3),
	  (104,'FALLA',4),
	  (105,'BHESAN',5),
	  (106,'DHORAJI',5);

SELECT * FROM VILLAGE

--1
SELECT V.VILLAGENAME
FROM CITY C
FULL OUTER JOIN VILLAGE V
ON C.CITYID = V.CITYID
WHERE C.CITYNAME = 'RAJKOT'

--2
SELECT C.CITYNAME,C.PINCODE,V.VILLAGENAME
FROM CITY C
RIGHT OUTER JOIN VILLAGE V
ON C.CITYID = V.CITYID

--3
SELECT CITY.CITYNAME,COUNT(VILLAGE.CITYID) AS NOOFVILLAGES
FROM CITY
LEFT OUTER JOIN VILLAGE 
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME
HAVING COUNT(VILLAGE.CITYID)>1

--4
SELECT CITY.CITYNAME
FROM CITY
LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME
HAVING COUNT(VILLAGE.CITYID)=0

--5
SELECT CITY.CITYNAME,COUNT(VILLAGE.VILLAGEID) AS TOTALVILLAGES
FROM CITY 
LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.CITYNAME

--6
SELECT COUNT(*)
FROM(SELECT CITY.[CITYNAME],
			COUNT(VILLAGE.CITYID) AS TOTAL
	FROM CITY LEFT OUTER JOIN VILLAGE 
	ON CITY.CITYID = VILLAGE.CITYID
	GROUP BY CITY.[CITYNAME]
	)AS T
	WHERE TOTAL>1



