--1
DELETE FROM CUSTOMERS WHERE CITY = 'BOMBAY'

--2
DELETE FROM DEPOSIT WHERE AMOUNT <= 1000

--3
DELETE FROM BORROW WHERE BNAME = 'AJNI'

--4
DELETE FROM BORROW WHERE LOANNO > 201 AND LOANNO < 210

--5
DELETE FROM DEPOSIT WHERE ADATE > '1996-12-01'

--6
TRUNCATE TABLE CUSTOMERS

--7
DELETE FROM DEPOSIT WHERE CNAME = 'AJNI' AND ACTNO = 101

--8
DELETE FROM DEPOSIT WHERE BNAME <> 'ANDHERI'

--9
DELETE FROM BORROW WHERE AMOUNT < 200 AND BNAME <> 'VRCE'

--10
DROP TABLE BRANCH
