--1
UPDATE DEPOSIT SET AMOUNT = 5000
WHERE AMOUNT=3000

--2
UPDATE BORROW SET BNAME = 'C.G.ROAD'
WHERE CNAME= 'ANIL'

--3
UPDATE DEPOSIT SET ACTNO= 111, AMOUNT = 5000
WHERE CNAME ='SANDIP'

--4
UPDATE BORROW SET AMOUNT =AMOUNT + (AMOUNT*10/100)

--5
UPDATE DEPOSIT SET AMOUNT = 5000
WHERE ACTNO>103 AND ACTNO<107

--6
UPDATE BORROW SET AMOUNT = NULL
WHERE LOANNO = 321

--7
UPDATE BORROW SET LOANNO = 401, BNAME = 'AJNI'
WHERE LOANNO = 401 AND BNAME ='VRCE'

--8
UPDATE CUSTOMERS SET CNAME = 'ANIL JAIN'
WHERE CNAME= 'ANIL'

--9
UPDATE DEPOSIT SET CNAME = 'RAMESH',BNAME = 'VRCE', AMOUNT=5500
WHERE  ACTNO =102

--10
UPDATE BORROW SET BNAME = NULL , AMOUNT = NULL
WHERE LOANNO = 481 AND CNAME = 'KRANTI'
