CREATE TABLE STUDENT
(ENROLLMENT_NO VARCHAR(50),
NAME VARCHAR(25),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME);

--1
ALTER TABLE STUDENT ADD CITY VARCHAR(20),BACKLOG INT

--2
ALTER TABLE STUDENT ALTER COLUMN NAME VARCHAR(35)

--3
ALTER TABLE STUDENT ALTER COLUMN CPI INT

--4
SP_RENAME 'STUDENT.ENROLLMENT_NO','ANO','COLUMN'

--5
ALTER TABLE STUDENT DROP COLUMN CITY

--6
SP_RENAME 'STUDENT','STUDENT_MASTER'

--7
ALTER TABLE STUDENT DROP COLUMN BACKLOG

--8
ALTER TABLE STUDENT ALTER COLUMN NAME VARCHAR(25) NOT NULL

--9
SP_RENAME 'STUDENT.BIRTHDATE','BDATE','COLUMN'

--10
ALTER TABLE STUDENT ALTER COLUMN ENO VARCHAR(12)
