CREATE TABLE EMPLOYEE
(EID INT,
ENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(8,2),
JOININGDATE DATETIME,
CITY VARCHAR(50));

INSERT INTO EMPLOYEE
VALUES(101,'RAHUL','ADMIN',56000,'1-JAN-90','RAJKOT'),
	  (102,'HARDIK','IT',18000,'25-SEP-90','AHMEDABAD'),
	  (103,'BHAVIN','HR',25000,'14-MAY-91','BARODA'),
	  (104,'BHOOMI','ADMIN',39000,'8-FEB-91','RAJKOT'),
	  (105,'ROHIT','IT',17000,'23-JUL-90','JAMNAGAR'),
	  (106,'PRIYA','IT',9000,'18-OCT-90','AHMEDABAD'),
	  (107,'NEHA','HR',34000,'25-DEC-91','RAJKOT');

SELECT * FROM EMPLOYEE


--1
SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM, AVG(SALARY), AS AVG_SAL,SUM(SALARY) AS TOTAL_SAL
FROM EMPLOYEE

--2
SELECT COUNT(*) as TOTALEMP FOM EMPLOYEE

--3
SELECT MAX(SALARY) AS MAX_SAL
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT'

--4
SELECT COUNT(DISTINCT CITY) AS UNQ_CITY
FROM EMPLOYEE

--5
SELECT CITY, COUNT(ENAME) AS TOTAL_EMP
FROM EMPLOYEE GROUP BY CITY

--6
SELECT CITY, COUNT(ENAME) As TotalEmp
FROM EMPLOYEE
GROUP BY CITY
HAVING COUNT(ENAME)>1

--7
SELECT DEPARTMENT, SUM(SALARY) As TotalSal
FROM EMPLOYEE
GROUP BY DEPARTMENT

--8
SELECT AVG(SALARY) AS AVG_SAL
FROM EMPLOYEE 
GROUP BY DEPARTMENT

--9
SELECT MIN(SALARY) AS MIN_SAL
FROM EMPLOYEE
WHERE CITY = 'AHMEDABAD'

--10
SELECT DEPARTMENT,SUM(SALARY) AS TOTALSAL
FROM EMPLOYEE
WHERE CITY = 'RAJKOT'
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>50000

--11
SELECT COUNT(ENAME) AS TOTALEMP
FROM EMPLOYEE
WHERE CITY ='RAJKOT'

--12
SELECT MAX(SALARY)-MIN(SALARY) AS 'SAL_DIFFERENCE'
FROM EMPLOYEE

--13
SELECT COUNT(*)AS TOTAL
FROM EMPLOYEE
WHERE JOININGDATE<'1991-01-01'

--14
SELECT DEPARTMENT,SUM(SALARY) AS TOTALSAL
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>35000
ORDER BY SUM(SALARY)

--15
SELECT DEPARTMENT,COUNT(*) AS TOTALEMP
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING COUNT(EID)>2

--16
SELECT MIN(SALARY) AS MINIMUM
FROM EMPLOYEE
WHERE CITY = 'RAJKOT'

--17
SELECT CITY,COUNT(*) AS TOTALEMPLOYEE
FROM EMPLOYEE
GROUP BY CITY

--18
SELECT DEPARTMENT,MIN(SALARY) AS MINIMUM
FROM EMPLOYEE
GROUP BY DEPARTMENT

--19
SELECT SUM(SALARY) AS TOTALSAL
FROM EMPLOYEE
GROUP BY CITY

--20
SELECT DEPARTMENT,MIN(SALARY) AS MINIMUM,MAX(SALARY) AS MAXIMUM,SUM(SALARY) AS TOTAL
FROM EMPLOYEE
GROUP BY DEPARTMENT

