CREATE TABLE COMPUTER
(ROLLNO INT,
NAME VARCHAR(50));

INSERT INTO COMPUTER
VALUES(101,'AJAY'),
	  (109,'HARESH'),
	  (115,'MANISH');

SELECT * FROM COMPUTER

CREATE TABLE ELECTRICAL
(ROLLNO INT,
NAME VARCHAR(50));

INSERT INTO ELECTRICAL
VALUES(105,'AJAY'),
	  (107,'MAHESH'),
	  (115,'MANISH');

SELECT * FROM ELECTRICAL

--1
SELECT NAME FROM COMPUTER
UNION
SELECT NAME FROM ELECTRICAL

--2
SELECT * FROM COMPUTER
UNION ALL
SELECT * FROM ELECTRICAL

--3
SELECT NAME FROM COMPUTER
INTERSECT
SELECT NAME FROM ELECTRICAL

--4
SELECT NAME FROM COMPUTER
EXCEPT
SELECT NAME FROM ELECTRICAL

--5
SELECT NAME FROM ELECTRICAL
EXCEPT
SELECT NAME FROM COMPUTER

--6
SELECT * FROM COMPUTER
UNION
SELECT * FROM ELECTRICAL

--7
SELECT * FROM COMPUTER
INTERSECT
SELECT * FROM ELECTRICAL



--INTO

CREATE TABLE CRICKET
(NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT);

INSERT INTO CRICKET
VALUES('SACHIN TENDULKAR','MUMBAI',30),
	  ('RAHUL DAVID','BOMBAY',35),
	  ('M.S.DHONI','JHARKHAND',31),
	  ('SURESH RAINA','GUJARAT',30);

SELECT * FROM CRICKET

--SELECT INTO

--1
SELECT * INTO WORLDCUP FROM CRICKET

SELECT * FROM WORLDCUP
 
--2
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=2

--3
SELECT * INTO IPL FROM CRICKET WHERE 1<>1

--4
INSERT INTO IPL SELECT * FROM CRICKET WHERE NAME LIKE '_A_____'

--5
DELETE FROM IPL

--6
DELETE FROM CRICKET WHERE CITY= 'JHARKHAND'

SELECT * FROM CRICKET

--7
SP_RENAME 'IPL','IPL2018'

--8
DROP TABLE T20